import { Link, createFileRoute } from '@tanstack/react-router'
import { getPipelineJob } from '@/lib/data/api/pipelines'
import { PageBody, PageHeader } from '@/components/phlo/page'
import { EmptyState } from '@/components/phlo/states'
import { Badge } from '@/components/ui/badge'

type Search = { env?: 'staging'; run?: string }

export const Route = createFileRoute('/_app/pipelines/$jobName')({
  validateSearch: (search: Record<string, unknown>): Search => ({ ...(search.env === 'staging' ? { env: 'staging' as const } : {}), ...(typeof search.run === 'string' ? { run: search.run } : {}) }),
  loaderDeps: ({ search }) => ({ env: search.env ?? ('prod' as const), run: search.run }),
  loader: ({ params, deps }) => getPipelineJob({ data: { id: params.jobName, env: deps.env, runId: deps.run } }),
  head: ({ params }) => ({ meta: [{ title: `${params.jobName} · phlo` }] }), component: JobPage,
})

function JobPage() {
  const { env, job, schedules, runs, summary, patterns, selectedRun, events, logs } = Route.useLoaderData()
  return <><PageHeader crumbs={[{ label: 'Pipelines', to: '/pipelines' }]} title={<span className="font-mono text-[14px]">{job.id}</span>} meta={`${env} · ${job.repository_name}`} />
    <PageBody>
      <section className="rounded-lg border border-border-card p-4"><h2 className="m-0 text-sm font-medium">Job evidence</h2><dl className="mt-3 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-xs text-muted-foreground">Description</dt><dd className="mt-1">{job.description ?? 'No description supplied'}</dd></div><div><dt className="text-xs text-muted-foreground">Selected assets</dt><dd className="mt-1 font-mono text-xs">{job.selected_assets.length ? job.selected_assets.map((path) => path.join('/')).join(', ') : 'No selected assets'}</dd></div><div><dt className="text-xs text-muted-foreground">Schedules</dt><dd className="mt-1">{schedules.length ? schedules.map((item) => <Badge key={item.id} variant="neutral" className="mr-1">{item.id}: {item.status}</Badge>) : 'No schedule evidence'}</dd></div><div><dt className="text-xs text-muted-foreground">Summary scan</dt><dd className="mt-1">{summary.scanned_runs} run records scanned</dd></div></dl></section>
      <section><h2 className="m-0 text-sm font-medium">Run status counts</h2><div className="mt-2 flex flex-wrap gap-2">{Object.entries(summary.counts_by_status).length ? Object.entries(summary.counts_by_status).map(([status, count]) => <Badge key={status} variant="neutral">{status}: {count}</Badge>) : 'No run status evidence'}</div></section>
      <section><h2 className="m-0 text-sm font-medium">Patterns</h2>{patterns.items.length ? <ul className="mt-2 space-y-2 text-sm">{patterns.items.map((item) => <li key={item.kind} className="rounded-lg border border-border-card p-3"><strong>{item.kind === 'failure' ? 'Failures' : 'Slow runs'}: {item.count}</strong>{typeof item.typical_duration_seconds === 'number' ? <span className="ml-2 text-muted-foreground">Typical duration: {item.typical_duration_seconds}s</span> : null}</li>)}</ul> : <p className="mt-2 text-sm text-muted-foreground">No patterns returned from {patterns.scanned_runs} scanned run records.</p>}</section>
      <section><h2 className="m-0 text-sm font-medium">Run records returned</h2>{runs.length ? <div className="mt-2 overflow-x-auto rounded-lg border border-border-card"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b border-line bg-raised text-xs text-muted-foreground"><th className="px-3 py-2">Run ID</th><th className="px-3 py-2">Status</th><th className="px-3 py-2">Created</th><th className="px-3 py-2">Duration</th><th className="px-3 py-2">Events</th></tr></thead><tbody>{runs.map((item) => <tr key={item.run_id} className="border-b border-line-soft last:border-0"><td className="px-3 py-3 font-mono text-xs">{item.run_id}</td><td className="px-3 py-3"><Badge variant="neutral">{item.status}</Badge></td><td className="px-3 py-3 font-mono text-xs text-muted-foreground">{item.created_at}</td><td className="px-3 py-3 font-mono text-xs text-muted-foreground">{item.duration_seconds === null ? 'Unavailable' : `${item.duration_seconds}s`}</td><td className="px-3 py-3"><Link to="/pipelines/$jobName" params={{ jobName: job.id }} search={{ env: env === 'staging' ? env : undefined, run: item.run_id }} className="text-link">Inspect timeline</Link></td></tr>)}</tbody></table></div> : <EmptyState title="No run records returned">The API did not return run evidence for this job.</EmptyState>}</section>
      {events ? <section><h2 className="m-0 text-sm font-medium">Run event timeline · <span className="font-mono text-xs">{events.run_id}</span></h2>{events.items.length ? <ol className="mt-2 space-y-2 border-l border-line pl-4 text-sm">{events.items.map((event, index) => <li key={`${event.timestamp}-${index}`}><span className="font-mono text-xs text-muted-foreground">{event.timestamp}</span> · {event.event_type}{event.step_key ? ` · ${event.step_key}` : ''}<div className="text-text-2">{event.message}</div></li>)}</ol> : <p className="mt-2 text-sm text-muted-foreground">No events returned.</p>}{events.truncated ? <p className="text-xs text-muted-foreground">Event response is truncated by the API.</p> : null}</section> : null}
      {logs && selectedRun ? <section><h2 className="m-0 text-sm font-medium">Logs · <span className="font-mono text-xs">{selectedRun.run_id}</span></h2><p className="mt-2 text-xs text-muted-foreground">{logs.is_terminal ? 'Terminal run' : 'Run is not terminal'} · {logs.follow_supported ? 'following is supported by the API' : 'following is unavailable'}</p><pre className="mt-2 max-h-64 overflow-auto rounded-lg border border-border-card bg-sunken p-3 text-xs whitespace-pre-wrap">{logs.items.length ? logs.items.map((item) => `[${item.timestamp}] ${item.message}`).join('\n') : 'No log events returned.'}</pre></section> : null}
      <p className="m-0 text-xs text-muted-foreground">This screen has no schedule, launch, or retry actions. Those operations are intentionally not wired.</p>
    </PageBody></>
}
