/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppBranchesRouteImport } from './routes/_app/branches'
import { Route as AppQueryRouteImport } from './routes/_app/query'
import { Route as AppStagingRouteImport } from './routes/_app/staging'
import { Route as AppAssetsIndexRouteImport } from './routes/_app/assets/index'
import { Route as AppAssetsAssetIdRouteImport } from './routes/_app/assets/$assetId'
import { Route as AppIncidentsIndexRouteImport } from './routes/_app/incidents/index'
import { Route as AppIncidentsIncidentIdRouteImport } from './routes/_app/incidents/$incidentId'
import { Route as AppPipelinesIndexRouteImport } from './routes/_app/pipelines/index'
import { Route as AppPipelinesJobNameRouteImport } from './routes/_app/pipelines/$jobName'
import { Route as AppPipelinesTimelineRouteImport } from './routes/_app/pipelines/timeline'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsAuditLogRouteImport } from './routes/_app/settings/audit-log'
import { Route as AppSettingsMembersRouteImport } from './routes/_app/settings/members'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBranchesRoute = AppBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AppRoute,
} as any)
const AppQueryRoute = AppQueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => AppRoute,
} as any)
const AppStagingRoute = AppStagingRouteImport.update({
  id: '/staging',
  path: '/staging',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsIndexRoute = AppAssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsAssetIdRoute = AppAssetsAssetIdRouteImport.update({
  id: '/assets/$assetId',
  path: '/assets/$assetId',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsIndexRoute = AppIncidentsIndexRouteImport.update({
  id: '/incidents/',
  path: '/incidents/',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsIncidentIdRoute = AppIncidentsIncidentIdRouteImport.update({
  id: '/incidents/$incidentId',
  path: '/incidents/$incidentId',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelinesIndexRoute = AppPipelinesIndexRouteImport.update({
  id: '/pipelines/',
  path: '/pipelines/',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelinesJobNameRoute = AppPipelinesJobNameRouteImport.update({
  id: '/pipelines/$jobName',
  path: '/pipelines/$jobName',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelinesTimelineRoute = AppPipelinesTimelineRouteImport.update({
  id: '/pipelines/timeline',
  path: '/pipelines/timeline',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAuditLogRoute = AppSettingsAuditLogRouteImport.update({
  id: '/settings/audit-log',
  path: '/settings/audit-log',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsMembersRoute = AppSettingsMembersRouteImport.update({
  id: '/settings/members',
  path: '/settings/members',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/branches': typeof AppBranchesRoute
  '/query': typeof AppQueryRoute
  '/staging': typeof AppStagingRoute
  '/assets/$assetId': typeof AppAssetsAssetIdRoute
  '/incidents/$incidentId': typeof AppIncidentsIncidentIdRoute
  '/pipelines/$jobName': typeof AppPipelinesJobNameRoute
  '/pipelines/timeline': typeof AppPipelinesTimelineRoute
  '/settings/audit-log': typeof AppSettingsAuditLogRoute
  '/settings/members': typeof AppSettingsMembersRoute
  '/assets/': typeof AppAssetsIndexRoute
  '/incidents/': typeof AppIncidentsIndexRoute
  '/pipelines/': typeof AppPipelinesIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/branches': typeof AppBranchesRoute
  '/query': typeof AppQueryRoute
  '/staging': typeof AppStagingRoute
  '/': typeof AppIndexRoute
  '/assets/$assetId': typeof AppAssetsAssetIdRoute
  '/incidents/$incidentId': typeof AppIncidentsIncidentIdRoute
  '/pipelines/$jobName': typeof AppPipelinesJobNameRoute
  '/pipelines/timeline': typeof AppPipelinesTimelineRoute
  '/settings/audit-log': typeof AppSettingsAuditLogRoute
  '/settings/members': typeof AppSettingsMembersRoute
  '/assets': typeof AppAssetsIndexRoute
  '/incidents': typeof AppIncidentsIndexRoute
  '/pipelines': typeof AppPipelinesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/branches': typeof AppBranchesRoute
  '/_app/query': typeof AppQueryRoute
  '/_app/staging': typeof AppStagingRoute
  '/_app/': typeof AppIndexRoute
  '/_app/assets/$assetId': typeof AppAssetsAssetIdRoute
  '/_app/incidents/$incidentId': typeof AppIncidentsIncidentIdRoute
  '/_app/pipelines/$jobName': typeof AppPipelinesJobNameRoute
  '/_app/pipelines/timeline': typeof AppPipelinesTimelineRoute
  '/_app/settings/audit-log': typeof AppSettingsAuditLogRoute
  '/_app/settings/members': typeof AppSettingsMembersRoute
  '/_app/assets/': typeof AppAssetsIndexRoute
  '/_app/incidents/': typeof AppIncidentsIndexRoute
  '/_app/pipelines/': typeof AppPipelinesIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/branches'
    | '/query'
    | '/staging'
    | '/assets/$assetId'
    | '/incidents/$incidentId'
    | '/pipelines/$jobName'
    | '/pipelines/timeline'
    | '/settings/audit-log'
    | '/settings/members'
    | '/assets/'
    | '/incidents/'
    | '/pipelines/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/branches'
    | '/query'
    | '/staging'
    | '/'
    | '/assets/$assetId'
    | '/incidents/$incidentId'
    | '/pipelines/$jobName'
    | '/pipelines/timeline'
    | '/settings/audit-log'
    | '/settings/members'
    | '/assets'
    | '/incidents'
    | '/pipelines'
    | '/settings'
  id:
    | '__root__'
    | '/_app'
    | '/_app/branches'
    | '/_app/query'
    | '/_app/staging'
    | '/_app/'
    | '/_app/assets/$assetId'
    | '/_app/incidents/$incidentId'
    | '/_app/pipelines/$jobName'
    | '/_app/pipelines/timeline'
    | '/_app/settings/audit-log'
    | '/_app/settings/members'
    | '/_app/assets/'
    | '/_app/incidents/'
    | '/_app/pipelines/'
    | '/_app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/branches': {
      id: '/_app/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AppBranchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/query': {
      id: '/_app/query'
      path: '/query'
      fullPath: '/query'
      preLoaderRoute: typeof AppQueryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staging': {
      id: '/_app/staging'
      path: '/staging'
      fullPath: '/staging'
      preLoaderRoute: typeof AppStagingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/': {
      id: '/_app/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AppAssetsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/$assetId': {
      id: '/_app/assets/$assetId'
      path: '/assets/$assetId'
      fullPath: '/assets/$assetId'
      preLoaderRoute: typeof AppAssetsAssetIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/incidents/': {
      id: '/_app/incidents/'
      path: '/incidents'
      fullPath: '/incidents/'
      preLoaderRoute: typeof AppIncidentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/incidents/$incidentId': {
      id: '/_app/incidents/$incidentId'
      path: '/incidents/$incidentId'
      fullPath: '/incidents/$incidentId'
      preLoaderRoute: typeof AppIncidentsIncidentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipelines/': {
      id: '/_app/pipelines/'
      path: '/pipelines'
      fullPath: '/pipelines/'
      preLoaderRoute: typeof AppPipelinesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipelines/$jobName': {
      id: '/_app/pipelines/$jobName'
      path: '/pipelines/$jobName'
      fullPath: '/pipelines/$jobName'
      preLoaderRoute: typeof AppPipelinesJobNameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipelines/timeline': {
      id: '/_app/pipelines/timeline'
      path: '/pipelines/timeline'
      fullPath: '/pipelines/timeline'
      preLoaderRoute: typeof AppPipelinesTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/audit-log': {
      id: '/_app/settings/audit-log'
      path: '/settings/audit-log'
      fullPath: '/settings/audit-log'
      preLoaderRoute: typeof AppSettingsAuditLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/members': {
      id: '/_app/settings/members'
      path: '/settings/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AppSettingsMembersRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBranchesRoute: typeof AppBranchesRoute
  AppQueryRoute: typeof AppQueryRoute
  AppStagingRoute: typeof AppStagingRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAssetsAssetIdRoute: typeof AppAssetsAssetIdRoute
  AppIncidentsIncidentIdRoute: typeof AppIncidentsIncidentIdRoute
  AppPipelinesJobNameRoute: typeof AppPipelinesJobNameRoute
  AppPipelinesTimelineRoute: typeof AppPipelinesTimelineRoute
  AppSettingsAuditLogRoute: typeof AppSettingsAuditLogRoute
  AppSettingsMembersRoute: typeof AppSettingsMembersRoute
  AppAssetsIndexRoute: typeof AppAssetsIndexRoute
  AppIncidentsIndexRoute: typeof AppIncidentsIndexRoute
  AppPipelinesIndexRoute: typeof AppPipelinesIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBranchesRoute: AppBranchesRoute,
  AppQueryRoute: AppQueryRoute,
  AppStagingRoute: AppStagingRoute,
  AppIndexRoute: AppIndexRoute,
  AppAssetsAssetIdRoute: AppAssetsAssetIdRoute,
  AppIncidentsIncidentIdRoute: AppIncidentsIncidentIdRoute,
  AppPipelinesJobNameRoute: AppPipelinesJobNameRoute,
  AppPipelinesTimelineRoute: AppPipelinesTimelineRoute,
  AppSettingsAuditLogRoute: AppSettingsAuditLogRoute,
  AppSettingsMembersRoute: AppSettingsMembersRoute,
  AppAssetsIndexRoute: AppAssetsIndexRoute,
  AppIncidentsIndexRoute: AppIncidentsIndexRoute,
  AppPipelinesIndexRoute: AppPipelinesIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
